name: DynamicDungeon
main: me.blackphreak.dynamicdungeon.DynamicDungeon
version: 1.0.0.0-1715
author: BlackPhreak
depend: [MythicMobs,AsyncWorldEdit, WorldEdit]
commands:
  dynamicdungeon:
    description: Plugin commands + Admin commands
    aliases: [dd]
permissions:
  dynamicdungeon.admin:
    description: Allow to use admin commands
  dynamicdungeon.player:
    description: Allow to use command