name: DynamicDungeon
main: me.blackphreak.dynamicdungeon.DynamicDungeon
version: 1.0.1.1-1826
authors: [BlackPhreak, caxerx]
depend: [MythicMobs, FastAsyncWorldEdit, WorldEdit]
softdepend: [HolographicDisplays]
commands:
  dynamicdungeon:
    description: Plugin commands + Admin commands
    aliases: [dd]
  dynamicdungeoneditor:
    description: editor command
    aliases: [dde]

permissions:
  dynamicdungeon.admin:
    description: Allow to use admin commands
  dynamicdungeon.player:
    description: Allow to use command